### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jackyliang** [evanyeung/terminal-slack#17]
What are the installation instructions?

**Comment by anth12** [comment]
First of all you need to obtain an API key (https://api.slack.com/docs/oauth-test-tokens) and save the key to your environment variables: `setx SLACK_TOKEN {{Token}}`

You will then need to clone or download as zip and run `node main.js`- no need for `npm install` as the node_modules folder is included in the repo.

**Comment by anxiousmodernman** [comment]
I stubbed out a bash script that:

* clones under *~/.terminal-slack*
* generates a wrapper script *terminal-slack.sh*
* puts a symlink in */usr/local/bin* to *~/.terminal-slack/terminal-slack.sh*

This is good enough for me on OSX, but the script needs more error-handling and environment checks. (e.g., it's not idempotent, and it assumes you have node on your PATH already)

https://gist.github.com/anxiousmodernman/80a7bf84f5c9a676e5de72d8ecc987e8

**Comment by evanyeung** [comment]
@jackyliang These are outlined in the readme. You should be able to clone the repo from https://github.com/evanyeung/terminal-slack.git and follow the directions in the **Setup** portion of the readme. Is there anything that is particularly unclear?

**Comment by evanyeung** [comment]
Updated the Readme to have better installation instructions. This can be re-opened (or a new issue can be created in the future) if this is still a problem.
