### ISSUE TITLE
`node main.js` opens Slack and closes it immediately....back to terminal prompt

### ISSUE THREAD

**Issue by asinode** [evanyeung/terminal-slack#21]
I exported the slack token with the given `export` command and ran `node main.js`. It opens slack for a fraction of a second and closes it immediately. I am not sure what went wrong.

Also, if I restarted my terminal session, the slack-token is asked again. It shows 
```
Error: SLACK_TOKEN undefined. Please add SLACK_TOKEN to the environment variables.
```

What am I doing wrong?

**Comment by guyfedwards** [comment]
When you restart your terminal the variables for that session are unset. You will need to add them to your `.bash_profile` or `.bashrc` so they are set for every session.

**Comment by asinode** [comment]
Thanks. I added SLACK_CLIENT in the `.bashrc` instead of SLACK_TOKEN. My mistake!
