### ISSUE TITLE
private channels doesn't work

### ISSUE THREAD

**Issue by Johnybe** [evanyeung/terminal-slack#24]
Hello,

I can't see my private channels
I can't see users of channels

Is there a way ?

Regards

**Comment by sadatnfs** [comment]
I concur, having this would be awesome!

**Comment by grifball** [comment]
Looks like you have to use the groups.list command:
https://api.slack.com/methods/groups.list

**Comment by grifball** [comment]
I ended up using brileb73's fork. Haven't fully tested it, but it seems to work
#35 
repo: https://github.com/brileb73/terminal-slack
branch: add-groups
commit: d58f448432fb516e2de4966791e18052bbc2b4ef
This ticket seems to be a duplicate of #22

**Comment by kukyo** [comment]
Hi, I'm new to terminal. How can I make private  channel available? I can't understand

**Comment by grifball** [comment]
Use this fork. Apparently private channels work:
https://github.com/omnibrian/terminal-slack/
It's also in my fork:
https://github.com/grifball/terminal-slack/

**Comment by kukyo** [comment]
> Use this fork. Apparently private channels work:
> https://github.com/omnibrian/terminal-slack/
> It's also in my fork:
> https://github.com/grifball/terminal-slack/

Thank you, I'll try it right now!
