### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by asbjornenge** [evanyeung/terminal-slack#3]
Hi! This looks awesome!! Is there any chance you eventually will publish this as a package to npm? I would love to be able to install it easily. If the app is not ready, I would love a ping on this issue when it is :smile: If you need any help publishing, let me know :+1: :wave:

**Comment by nikolay** [comment]
Even if not published to npm, it would be nice to add a `package.json` instead of bundling third-party code in.

**Comment by evanyeung** [comment]
@nikolay Thanks for bringing that up. I've added one.

@asbjornenge this was a pretty quick weekend project and is still a ways from publishing. If I eventually decide to, I'll let you know. Until then, the package.json should help a lot. Thanks for the interest!
