### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by irishman2020** [evanyeung/terminal-slack#34]
I get the following error on first load:
`let users;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
'
I also get the following errors on npm install:

'npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
'
Environment: 
4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by derhuerst** [comment]
What is your Node.js version?

**Comment by irishman2020** [comment]
v4.2.6, just grabbed it from apt-get on 16.04

**Comment by derhuerst** [comment]
It looks a lot like you need Node 6+ to run this. [Nodesource is your friend](https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions).

**Comment by irishman2020** [comment]
derhuerst: that resolved it, closing. Thanks!

**Comment by sylvainhalle** [comment]
The version requirement on Node should be written in the Readme. Ubuntu 16.04 installs 4.x by default.

**Comment by evanyeung** [comment]
You're right. I've updated the readme to include the minimum Node version. Thanks!
