### ISSUE TITLE
register as npm global package

### ISSUE THREAD

**Issue by mike3run** [evanyeung/terminal-slack#43]
So we can update easily and without cloning the repo

**Comment by derhuerst** [comment]
Note that you can [use npm to install from GitHub repos, including Git commits and tags](https://docs.npmjs.com/cli/install).

**Comment by evanyeung** [comment]
This was actually suggested in #3. As @derhuerst notes, it doesn't need to be added to npm for you to download it without cloning the repo. This might be worth adding in the README if you find it much more convenient than cloning.

**Comment by adius** [comment]
This should really be mentioned in the readme ^^
