### ISSUE TITLE
Slack API Permission

### ISSUE THREAD

**Issue by Mahezerlabs** [evanyeung/terminal-slack#47]
Hi, I set everything up for my Slack API, but I can't figure out what OAuth permissions to give to my token....
I keep receiving `Error: missing_scope` whenever I run `node main.js`

**Comment by mootaccount** [comment]
Could it be because it only supports the legacy Slack token?

**Comment by Mahezerlabs** [comment]
Dunno, I don't actually know much about slack integration nor this repo....

**Comment by evanyeung** [comment]
This repo isn't set up for OAuth at all. The instructions for set up are in the README and use the legacy Slack token.

**Comment by evanyeung** [comment]
This repo isn't set up for OAuth at all. The instructions for set up are in the README and use the legacy Slack token.

**Comment by evanyeung** [comment]
This repo isn't set up for OAuth at all. The instructions for set up are in the README and use the legacy Slack token.

**Comment by Mahezerlabs** [comment]
Understood. I kinda failed at reading the docs...
