### ISSUE TITLE
node main.js doesn't start

### ISSUE THREAD

**Issue by GitHamo** [evanyeung/terminal-slack#48]
Hi Evan,

I have an issue. I'm sure npm and node are installed and meet the requirements but every time i try to run `node main.js` the app appears for one second and then it closes.

It shows that it's trying to connect to Slack before it closes again.

![image](https://user-images.githubusercontent.com/17246505/29662917-3af0cace-88c9-11e7-998d-132bfd1ea563.png)

Any idea how can i fix that?
Thanks in advance.

**Comment by mohnjatthews** [comment]
I have the exact same issue. Running OSX High Sierra. Were you able to find a fix @GitHamo ?
