### ISSUE TITLE
Unable to see input box when window is resized.

### ISSUE THREAD

**Issue by mohnjatthews** [evanyeung/terminal-slack#59]
If you resize the terminal window to less than 26 vertical lines, you're unable to see what's being typed in the input window. See the gif below:

![untitled](https://user-images.githubusercontent.com/9611008/33128088-0d79812a-cf83-11e7-91f5-04d9a0929667.gif)
From what I can tell changing the width of the terminal window doesn't really do anything.

**Comment by johnnymatthews** [comment]
Oh man, I should've closed this issue years ago. Sorry about that.
