### ISSUE TITLE
Persistent apis and multiple slack instances?

### ISSUE THREAD

**Issue by IanQS** [evanyeung/terminal-slack#60]
I am part of a few organizations and I'd like to be able to just save my tokens and select which one for which organization or something.

For context, I'm running multiple tmux sessions and within say section A I want to have one separate instance and within B i want to have another. Is this possible and if so is there a workflow or something I can take a look at?

**Comment by grifball** [comment]
This might be a good place to start:
https://github.com/evanyeung/terminal-slack/issues/54
There's a commit which should load up a .env file, you could easily modify it so that it reads in a .env filename from arguments and then use multiple .env files for different tokens.
